spring:
  config:
    activate:
      on-profile: prod
  datasource:
    maximum-pool-size: 4
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: ${RDS_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 1000
        show_sql: false

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    scope: profile_nickname, account_email

  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI}
    scope: name, email

  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect_uri: ${GOOGLE_REDIRECT_URI}
    scope: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email

 
jwt:
  secretKey: ${JWT_SECRETKEY}

  access:
    expiration: ${ACCESS_EXPIRATION} # 1시간
    header: ${ACCESS_HEADER}

  refresh:
    expiration: ${REFRESH_EXPIRATION} # 50일
    header: ${REFRESH_HEADER}
