spring:
  config:
    activate:
      on-profile: local
  datasource:
    maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/mapledb
    username: maple
    password: maple
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 985878687237-cicutlukd65ppl03l9cr1itf38fs66t4.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

          naver:
            client-id: VdrgQTkuTzW0ZzQ4KRf8
            client-secret: FrehdkhQpq
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

          kakao:
            client-id: 6cd76732b83c309a873e9789558b32cc
            client-secret: HeqZwFlX6QRnLny2TXgg4S1gA2RtUJ5t
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secretKey: alkjfio1jk3j1igasnafbvkanlsdfipo123kj1h51AASDFfggdfafsdbaQWEFGSDgasdfl23jopasd124~~

  access:
    expiration: 3600000 # 1시간
    header: Authorization

  refresh:
    expiration: 4320000000 # 50일
    header: ReAuthorization

