spring:
  config:
    activate:
      on-profile: local
  datasource:
    maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/mapledb
    username: maple
    password: maple
    driver-class-name: org.postgresql.Driver

oauth:
  kakao:
    client_id: 6cd76732b83c309a873e9789558b32cc
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret: HeqZwFlX6QRnLny2TXgg4S1gA2RtUJ5t
    scope: profile_nickname, account_email

  naver:
    client_id: VdrgQTkuTzW0ZzQ4KRf8
    redirect_uri: http://localhost:3000/oauth/redirected/naver
    client_secret: FrehdkhQpq
    scope: name, email
    state: alksdjflkqefnkl

  google:
    client-id: 985878687237-cicutlukd65ppl03l9cr1itf38fs66t4.apps.googleusercontent.com
    client-secret: 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
    redirect_uri: http://localhost:3000/oauth/redirected/google
    scope: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email


jwt:
  secretKey: alkjfio1jk3j1igasnafbvkanlsdfipo123kj1h51AASDFfggdfafsdbaQWEFGSDgasdfl23jopasd124~~

  access:
    expiration: 3600000 # 1시간
    header: Authorization

  refresh:
    expiration: 4320000000 # 50일
    header: ReAuthorization

